also check thumbnail image

diff --git a/.github/workflows/validate-drivers.yml b/.github/workflows/validate-drivers.yml
--- a/.github/workflows/validate-drivers.yml
+++ b/.github/workflows/validate-drivers.yml
@@ -62,7 +62,7 @@ jobs:
             exit 1
           done
 
-      - name: Validate manufacturer and category images exist
+      - name: Validate images exist
         run: |
           find src/content/docs/drivers -name "*.yaml" | while read -r yaml_file; do
             manufacturer=$(grep "Manufacturer:" "$yaml_file" | awk -F': ' '{print $2}' | tr -d '\r')
@@ -91,6 +91,20 @@ jobs:
               fi
             else
               echo "::error file=$md_file::Category name not found in '$md_file'."
+              exit 1
+            fi
+
+            thumbnail=$(grep "thumbnail:" "$md_file" | awk -F': ' '{print $2}' | tr -d '\r')
+            title=$(grep "title:" "$md_file" | awk -F': ' '{print $2}' | tr -d '\r')
+            if [ -n "$thumbnail" ]; then
+              thumbnail_slug=$(echo "$thumbnail" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--/-/g' | sed 's/^-//' | sed 's/-$//')
+              thumbnail_image="public${thumbnail_slug}.webp"
+              if [ ! -f "$thumbnail_image" ]; then
+                echo "::error file=$md_file::Thumbnail image for '$title' not found at '$thumbnail_image'."
+                exit 1
+              fi
+            else
+              echo "::error file=$md_file::Thumbnail image not found in '$md_file'."
               exit 1
             fi
           done
